stc_scraper_homepage:
    pattern:  /scraper
    defaults: { _controller: StcScraperBundle:Default:index }

index:
    pattern: /index
    defaults: { _controller: StcScraperBundle:Core:index }

stc_scraper_theme:
    pattern: /scraper/theme
    defaults: { _controller: StcScraperBundle:Default:theme }