parameters:
#    stc_scraper.example.class: Stc\ScraperBundle\Example

services:
#    stc_scraper.example:
#        class: %stc_scraper.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
